version: "3.0"
services:
  app:
    volumes:
      - "./:/app"
      - "./docker/php/.user.ini:/usr/local/etc/php/php.ini"
    working_dir: /app
    command: "php artisan serve --host=0.0.0.0 --port=8000"
    ports:
      - 8000:8000
    build:
      context: docker
      dockerfile: Dockerfile
  db:
    image: mariadb
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - 3307:3307
    volumes:
      - "db-data:/var/lib/mysql/data"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    restart: always
    ports:
      - 8080:80
    volumes:
      - /sessions
volumes:
  db-data: {}
